import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../components/Header/Header'
import ItemCardGrid from '../components/ItemCartGrid/ItemCartGrid'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-comm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Header />
        </div>
        <span>
          <Image src="/banner.jpg" alt="banner" width={2000} height={500} />
        </span>

        <div className={styles.cart}>
          <ItemCardGrid />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
